version: '3.4'

services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: src/Gateway/APIGateway/Dockerfile

  customer.api:
    image: ${DOCKER_REGISTRY-}customerapi
    build:
      context: .
      dockerfile: src/Services/Customer/Customer.API/Dockerfile
      
  order.api:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: src/Services/Order/Order.API/Dockerfile
      
  audit.consumer:
    image: ${DOCKER_REGISTRY-}auditconsumer
    build:
      context: .
      dockerfile: src/Consumers/Audit/Audit.Consumer/Dockerfile