name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  DOTNET_VERSION: "7.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      # Customer
      - name: Restore
        run: dotnet restore ./src/Services/Customer/Customer.API/Customer.API.csproj

      - name: Build
        run: dotnet build ./src/Services/Customer/Customer.API/Customer.API.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test ./src/Services/Customer/Customer.API/Customer.API.csproj --configuration Release --no-restore --no-build
      # Order
      - name: Restore
        run: dotnet restore ./src/Services/Order/Order.API/Order.API.csproj

      - name: Build
        run: dotnet build ./src/Services/Order/Order.API/Order.API.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test ./src/Services/Order/Order.API/Order.API.csproj --configuration Release --no-restore --no-build
      # Gateway
      - name: Restore
        run: dotnet restore ./src/Gateway/APIGateway/APIGateway.csproj

      - name: Build
        run: dotnet build ./src/Gateway/APIGateway/APIGateway.csproj --configuration Release --no-restore